/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@localhost:5432/my_app_db -t cr -t cr_in_version -t cr_to_shosh -t dependency -t pgmigrations -t project -t resp_user_in_project -t resp_user_in_shosh -t shosh -t user_to_cr -t users -t version -s public
 *
 */


export type Json = unknown;

// Table cr
export interface Cr {
  id: number;
  name: string;
  is_DDIC: boolean;
  environment: string;
  is_customization: boolean;
  is_released: boolean;
  is_documented: boolean;
}
export interface CrInput {
  id?: number;
  name: string;
  is_DDIC: boolean;
  environment: string;
  is_customization: boolean;
  is_released: boolean;
  is_documented: boolean;
}
const cr = {
  tableName: 'cr',
  columns: ['id', 'name', 'is_DDIC', 'environment', 'is_customization', 'is_released', 'is_documented'],
  requiredForInsert: ['name', 'is_DDIC', 'environment', 'is_customization', 'is_released', 'is_documented'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Cr,
  $input: null as unknown as CrInput
} as const;

// Table cr_in_version
export interface CrInVersion {
  cr_id: number;
  version_id: number;
  order_in_version: number;
}
export interface CrInVersionInput {
  cr_id: number;
  version_id: number;
  order_in_version: number;
}
const cr_in_version = {
  tableName: 'cr_in_version',
  columns: ['cr_id', 'version_id', 'order_in_version'],
  requiredForInsert: ['cr_id', 'version_id', 'order_in_version'],
  primaryKey: 'cr_id',
  foreignKeys: {
    cr_id: { table: 'cr', column: 'id', $type: null as unknown as Cr },
    version_id: { table: 'version', column: 'id', $type: null as unknown as Version },
  },
  $type: null as unknown as CrInVersion,
  $input: null as unknown as CrInVersionInput
} as const;

// Table cr_to_shosh
export interface CrToShosh {
  cr_id: number;
  shosh_id: number;
  description: string | null;
}
export interface CrToShoshInput {
  cr_id: number;
  shosh_id: number;
  description?: string | null;
}
const cr_to_shosh = {
  tableName: 'cr_to_shosh',
  columns: ['cr_id', 'shosh_id', 'description'],
  requiredForInsert: ['cr_id', 'shosh_id'],
  primaryKey: null,
  foreignKeys: {
    cr_id: { table: 'cr', column: 'id', $type: null as unknown as Cr },
    shosh_id: { table: 'shosh', column: 'id', $type: null as unknown as Shosh },
  },
  $type: null as unknown as CrToShosh,
  $input: null as unknown as CrToShoshInput
} as const;

// Table dependency
export interface Dependency {
  cr_id: number;
  depends_on_cr_id: number;
}
export interface DependencyInput {
  cr_id: number;
  depends_on_cr_id: number;
}
const dependency = {
  tableName: 'dependency',
  columns: ['cr_id', 'depends_on_cr_id'],
  requiredForInsert: ['cr_id', 'depends_on_cr_id'],
  primaryKey: null,
  foreignKeys: {
    cr_id: { table: 'cr', column: 'id', $type: null as unknown as Cr },
    depends_on_cr_id: { table: 'cr', column: 'id', $type: null as unknown as Cr },
  },
  $type: null as unknown as Dependency,
  $input: null as unknown as DependencyInput
} as const;

// Table pgmigrations
export interface Pgmigrations {
  id: number;
  name: string;
  run_on: Date;
}
export interface PgmigrationsInput {
  id?: number;
  name: string;
  run_on: Date;
}
const pgmigrations = {
  tableName: 'pgmigrations',
  columns: ['id', 'name', 'run_on'],
  requiredForInsert: ['name', 'run_on'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pgmigrations,
  $input: null as unknown as PgmigrationsInput
} as const;

// Table project
export interface Project {
  id: number;
  name: string;
}
export interface ProjectInput {
  id?: number;
  name: string;
}
const project = {
  tableName: 'project',
  columns: ['id', 'name'],
  requiredForInsert: ['name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Project,
  $input: null as unknown as ProjectInput
} as const;

// Table resp_user_in_project
export interface RespUserInProject {
  user_id: string;
  project_id: number;
}
export interface RespUserInProjectInput {
  user_id: string;
  project_id: number;
}
const resp_user_in_project = {
  tableName: 'resp_user_in_project',
  columns: ['user_id', 'project_id'],
  requiredForInsert: ['user_id', 'project_id'],
  primaryKey: null,
  foreignKeys: {
    user_id: { table: 'users', column: 'id', $type: null as unknown as Users },
    project_id: { table: 'project', column: 'id', $type: null as unknown as Project },
  },
  $type: null as unknown as RespUserInProject,
  $input: null as unknown as RespUserInProjectInput
} as const;

// Table resp_user_in_shosh
export interface RespUserInShosh {
  user_id: string;
  shosh_id: number;
}
export interface RespUserInShoshInput {
  user_id: string;
  shosh_id: number;
}
const resp_user_in_shosh = {
  tableName: 'resp_user_in_shosh',
  columns: ['user_id', 'shosh_id'],
  requiredForInsert: ['user_id', 'shosh_id'],
  primaryKey: null,
  foreignKeys: {
    user_id: { table: 'users', column: 'id', $type: null as unknown as Users },
    shosh_id: { table: 'shosh', column: 'id', $type: null as unknown as Shosh },
  },
  $type: null as unknown as RespUserInShosh,
  $input: null as unknown as RespUserInShoshInput
} as const;

// Table shosh
export interface Shosh {
  id: number;
  project_id: number;
  name: string;
  description: string | null;
  jira_url: string | null;
}
export interface ShoshInput {
  id?: number;
  project_id: number;
  name: string;
  description?: string | null;
  jira_url?: string | null;
}
const shosh = {
  tableName: 'shosh',
  columns: ['id', 'project_id', 'name', 'description', 'jira_url'],
  requiredForInsert: ['project_id', 'name'],
  primaryKey: 'id',
  foreignKeys: { project_id: { table: 'project', column: 'id', $type: null as unknown as Project }, },
  $type: null as unknown as Shosh,
  $input: null as unknown as ShoshInput
} as const;

// Table user_to_cr
export interface UserToCr {
  user_id: string;
  cr_id: number;
  relationship_type: string;
}
export interface UserToCrInput {
  user_id: string;
  cr_id: number;
  relationship_type: string;
}
const user_to_cr = {
  tableName: 'user_to_cr',
  columns: ['user_id', 'cr_id', 'relationship_type'],
  requiredForInsert: ['user_id', 'cr_id', 'relationship_type'],
  primaryKey: null,
  foreignKeys: {
    user_id: { table: 'users', column: 'id', $type: null as unknown as Users },
    cr_id: { table: 'cr', column: 'id', $type: null as unknown as Cr },
  },
  $type: null as unknown as UserToCr,
  $input: null as unknown as UserToCrInput
} as const;

// Table users
export interface Users {
  id: string;
  pernr: string;
  name: string;
  userType: string;
  imageUrl: string | null;
}
export interface UsersInput {
  id: string;
  pernr: string;
  name: string;
  userType: string;
  imageUrl?: string | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'pernr', 'name', 'userType', 'imageUrl'],
  requiredForInsert: ['id', 'pernr', 'name', 'userType'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;

// Table version
export interface Version {
  id: number;
  name: string;
  date: Date;
}
export interface VersionInput {
  id?: number;
  name: string;
  date: Date;
}
const version = {
  tableName: 'version',
  columns: ['id', 'name', 'date'],
  requiredForInsert: ['name', 'date'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Version,
  $input: null as unknown as VersionInput
} as const;


export interface TableTypes {
  cr: {
    select: Cr;
    input: CrInput;
  };
  cr_in_version: {
    select: CrInVersion;
    input: CrInVersionInput;
  };
  cr_to_shosh: {
    select: CrToShosh;
    input: CrToShoshInput;
  };
  dependency: {
    select: Dependency;
    input: DependencyInput;
  };
  pgmigrations: {
    select: Pgmigrations;
    input: PgmigrationsInput;
  };
  project: {
    select: Project;
    input: ProjectInput;
  };
  resp_user_in_project: {
    select: RespUserInProject;
    input: RespUserInProjectInput;
  };
  resp_user_in_shosh: {
    select: RespUserInShosh;
    input: RespUserInShoshInput;
  };
  shosh: {
    select: Shosh;
    input: ShoshInput;
  };
  user_to_cr: {
    select: UserToCr;
    input: UserToCrInput;
  };
  users: {
    select: Users;
    input: UsersInput;
  };
  version: {
    select: Version;
    input: VersionInput;
  };
}

export const tables = {
  cr,
  cr_in_version,
  cr_to_shosh,
  dependency,
  pgmigrations,
  project,
  resp_user_in_project,
  resp_user_in_shosh,
  shosh,
  user_to_cr,
  users,
  version,
}
